'use strict';
// figure-docs.test.js -- unit gate for the four DOCUMENT renderers in build/figure-gen-docs.js
// (timeline, facsimile, schematic, route), the renderers that let the three ELA reading packs
// carry built graphics generated from a committed dataTable.
//
// WHY BYTE-COMPARE IS NOT ENOUGH, AND WHAT ELSE IS HERE. tests/figure-derive.js proves
// REPRODUCIBILITY: it regenerates a figure from its own dataTable and compares bytes, so both
// sides come from the same generator and a bug IN the generator reproduces perfectly. The
// committed fixture .svg files below have the same blindness -- they were generated BY these
// renderers. That is exactly the 26-0822 histogram defect (a byte-compare cannot see a defect in
// the renderer, because the renderer made both sides), and two of the four defects that shipped
// that day were green in every gate. So this file carries three families of check that do NOT
// come from the generator:
//   1. STRUCTURAL invariants read out of the emitted SVG (viewBox, no <script>, no SMIL, no remote
//      href) -- properties the renderer could get wrong and a byte-compare would happily freeze.
//   2. GEOMETRY measured against the canvas: every <text> run's estimated extent must lie inside
//      the 800x450 viewBox, using the SAME width estimator figure-gen.js uses for its own margins.
//      A label past the edge is a data-truth defect, not a cosmetic one: the figure then displays
//      less than its dataTable says.
//   3. SEMANTIC invariants the plan makes requirements: the authored font floor, a redacted line
//      that draws a bar and NEVER text under it, an unverified event drawn dashed and marked, a
//      gap drawn as a band. Each is a thing a reader would be misled by if it silently stopped
//      working, and none is visible to a byte-compare.
// The fixture PNGs were also looked at by eye before the .svg files were committed as expected
// output (plan W0.1 step 3). A fixture nobody looked at is the 26-0822 histogram again.

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const docs = require('../build/figure-gen-docs.js');
const { genSvg, GLYPH_W, VB_W, VB_H } = require('../build/figure-gen.js');

const FIX = path.join(__dirname, 'fixtures', 'figure-docs');
const ACCENT = '#3a6';

let failures = 0;
function check(name, fn) {
  try { fn(); console.log('  ok   ' + name); }
  catch (e) { failures++; console.log('  FAIL ' + name + ': ' + e.message); }
}

function readFixture(base) {
  return JSON.parse(fs.readFileSync(path.join(FIX, base + '.json'), 'utf8'));
}
function readExpected(base) {
  // Committed with LF; a Windows checkout may hand back CRLF. Compare on LF, as
  // tests/figure-reconcile.js already does for the polygon SVGs.
  return fs.readFileSync(path.join(FIX, base + '.svg'), 'utf8').split('\r\n').join('\n');
}

// ---------------------------------------------------------------------------
// The eight fixtures, and which renderer and dispatch type each one exercises.
// Every branch a real ELA figure will take is represented: a timeline with two tracks AND one
// with a single track, a facsimile of ruled lines AND one of columns, a schematic laid out by
// the renderer (flow-lr) AND one honouring authored x/y (plan), a route as a loop AND as a line.
// A branch with no fixture has no positive control, and W0.2's derive controls inherit this set.
// ---------------------------------------------------------------------------
const CASES = [
  { base: 'timeline-two-track',  fn: 'renderTimeline',  type: 'timeline'  },
  { base: 'timeline-single',     fn: 'renderTimeline',  type: 'timeline'  },
  { base: 'facsimile',           fn: 'renderFacsimile', type: 'facsimile' },
  { base: 'facsimile-columns',   fn: 'renderFacsimile', type: 'facsimile' },
  { base: 'schematic-flow',      fn: 'renderSchematic', type: 'schematic' },
  { base: 'schematic-plan',      fn: 'renderSchematic', type: 'schematic' },
  { base: 'route-loop',          fn: 'renderRoute',     type: 'route'     },
  { base: 'route-line',          fn: 'renderRoute',     type: 'route'     },
];

// The AUTHORED font floor. figure-gen.js sizes text for the lightbox, where the worst case is the
// iPad 6 portrait viewport: 94vw of 768 CSS px = 721.92px against an 800px native width, i.e.
// 0.9024x, so an authored size must clear 15 / 0.9024 = 16.62px to render at the 15px floor. Its
// own smallest authored size is NOTE_FONT = 18. These renderers may not go below it.
const FONT_FLOOR = 18;

// Pull every text run out of an SVG string with the attributes needed to bound it horizontally.
function textRuns(svg) {
  const runs = [];
  // The attribute run is CAPTURED here; textContents() below deliberately does not capture it.
  const re = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  let m;
  while ((m = re.exec(svg)) !== null) {
    const attrs = m[1];
    const inner = m[2];
    // Anchored on a word boundary: an unanchored /y="([^"]*)"/ also matches the dy="" of a tspan,
    // which silently read every wrapped label's baseline as 0 and put it above the canvas.
    const get = (k) => {
      const a = new RegExp('(?:^|\\s)' + k + '="([^"]*)"').exec(attrs);
      return a ? a[1] : null;
    };
    const spans = [];
    let spanDy = 0;
    const spanRe = /<tspan\b([^>]*)>([\s\S]*?)<\/tspan>/g;
    let s;
    while ((s = spanRe.exec(inner)) !== null) {
      const sAttrs = s[1];
      const sGet = (k) => {
        const a = new RegExp('(?:^|\\s)' + k + '="([^"]*)"').exec(sAttrs);
        return a ? a[1] : null;
      };
      spanDy += sGet('dy') !== null ? parseFloat(sGet('dy')) : 0;
      spans.push({
        x: sGet('x') !== null ? parseFloat(sGet('x')) : (get('x') !== null ? parseFloat(get('x')) : 0),
        y: (get('y') !== null ? parseFloat(get('y')) : 0) + spanDy,
        fontSize: parseFloat(sGet('font-size') || get('font-size') || '0'),
        anchor: sGet('text-anchor') || get('text-anchor') || 'start',
        text: s[2],
      });
    }
    if (spans.length) { runs.push.apply(runs, spans); continue; }
    runs.push({
      x: get('x') !== null ? parseFloat(get('x')) : 0,
      y: get('y') !== null ? parseFloat(get('y')) : 0,
      fontSize: parseFloat(get('font-size') || '0'),
      anchor: get('text-anchor') || 'start',
      text: inner,
    });
  }
  return runs;
}

// Undo the four entities esc() writes, so a width estimate counts CHARACTERS a reader sees rather
// than the five of "&amp;". Overestimating width would make this check fire on figures that are
// actually fine, which is how a real gate gets disabled.
function unesc(s) {
  return String(s).replace(/&lt;/g, '<').replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"').replace(/&amp;/g, '&');
}

// The SAME estimator build/figure-gen.js uses for its own left margin (estimateTextWidth), rebuilt
// from the GLYPH_W constant it exports so the two can never disagree about how wide a label is.
function estWidth(text, fontSize) {
  return unesc(text).length * GLYPH_W * fontSize;
}

// The collapsed text content of each <text> element, tspans folded in. THIS is the level a fidelity
// check reads at, and the reason the renderers wrap with <tspan> inside one <text> rather than
// emitting one <text> per line: a label wrapped across two tspans is still that label, while a label
// split across two <text> elements does not exist in the document as a whole string at all.
function textContents(svg) {
  const out = [];
  const re = /<text\b[^>]*>([\s\S]*?)<\/text>/g;
  let m;
  while ((m = re.exec(svg)) !== null) {
    out.push(unesc(m[1].replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim());
  }
  return out;
}

function horizontalExtent(run) {
  const w = estWidth(run.text, run.fontSize);
  if (run.anchor === 'middle') return [run.x - w / 2, run.x + w / 2];
  if (run.anchor === 'end') return [run.x - w, run.x];
  return [run.x, run.x + w];
}

// ---------------------------------------------------------------------------
// 0. CONTROLS ON THIS FILE'S OWN MACHINERY.
// The canvas-containment and font-floor checks below are only worth their runtime if the parser
// feeding them actually reads the attributes it claims to. It did not, once: an attribute regex
// written as '(?:^|\s)' in a JS string literal compiles as '(?:^|s)', which matched nothing, so
// every baseline read as 0, the geometry check silently stopped measuring, and the suite went
// green BY GOING BLIND. These four controls fail if that happens again.
// ---------------------------------------------------------------------------
check('CONTROL: the parser actually reads x, y, font-size and text-anchor off a real element', () => {
  const runs = textRuns('<text x="40" y="44" font-size="26" fill="#e8eef7" text-anchor="middle">hi</text>');
  assert.strictEqual(runs.length, 1);
  assert.strictEqual(runs[0].x, 40, 'x was not read');
  assert.strictEqual(runs[0].y, 44, 'y was not read (an unanchored regex also matches dy=)');
  assert.strictEqual(runs[0].fontSize, 26, 'font-size was not read');
  assert.strictEqual(runs[0].anchor, 'middle', 'text-anchor was not read');
  assert.strictEqual(runs[0].text, 'hi');
});

check('CONTROL: a tspan baseline accumulates dy rather than reading dy as y', () => {
  const runs = textRuns('<text x="10" y="100" font-size="20" fill="#fff">'
    + '<tspan x="10" dy="0">one</tspan> <tspan x="10" dy="22">two</tspan></text>');
  assert.strictEqual(runs.length, 2);
  assert.strictEqual(runs[0].y, 100, 'first tspan should sit on the parent baseline');
  assert.strictEqual(runs[1].y, 122, 'second tspan should sit one line down, not at dy');
});

check('NEGATIVE CONTROL: text pushed off the canvas IS detected (the geometry check is armed)', () => {
  const off = '<text x="780" y="44" font-size="22" fill="#fff">a label far too wide to fit here</text>';
  const runs = textRuns(off);
  const ext = horizontalExtent(runs[0]);
  assert.ok(ext[1] > VB_W, 'a label running off the right edge was not measured as overflowing');
  const above = textRuns('<text x="40" y="4" font-size="22" fill="#fff">high</text>')[0];
  assert.ok(above.y - 0.8 * above.fontSize < 0, 'a label above the top edge was not measured as overflowing');
});

check('NEGATIVE CONTROL: a sub-floor font size IS detected', () => {
  const sizes = ('<text font-size="12">x</text>'.match(/font-size="([0-9.]+)"/g) || [])
    .map((s) => parseFloat(/"([0-9.]+)"/.exec(s)[1]));
  assert.deepStrictEqual(sizes.filter((s) => s < FONT_FLOOR), [12],
    'the font-floor scan does not actually find an undersized font');
});

// ---------------------------------------------------------------------------
// 1. The module's own interface
// ---------------------------------------------------------------------------
check('DOC_TYPES is exactly the four document types, in plan order', () => {
  assert.deepStrictEqual(docs.DOC_TYPES, ['timeline', 'facsimile', 'schematic', 'route']);
});

check('all four renderers are exported as functions of (dataTable, accent)', () => {
  ['renderTimeline', 'renderFacsimile', 'renderSchematic', 'renderRoute'].forEach((fn) => {
    assert.strictEqual(typeof docs[fn], 'function', fn + ' is not a function');
    assert.strictEqual(docs[fn].length, 2, fn + ' does not take exactly (dataTable, accent)');
  });
});

check('the canvas constants are the ones figure-gen.js already publishes', () => {
  assert.strictEqual(VB_W, 800);
  assert.strictEqual(VB_H, 450);
});

// The twin check that makes the token extraction safe. build/figure-tokens.js now OWNS the values
// build/figure-gen.js used to declare inline; if the two ever diverge, the chart path and the
// document path would draw the same pack in two different palettes and nothing else would notice.
// Same pattern tests/figures.test.js already uses for the FIG_KINDS / DOC_KINDS enum twins.
check('figure-tokens and figure-gen publish the SAME tokens (no drift between chart and doc paths)', () => {
  const tok = require('../build/figure-tokens.js');
  const gen = require('../build/figure-gen.js');
  ['INK', 'GRID', 'PLOT_GRID', 'DEFAULT_ACCENT', 'GLYPH_W', 'VB_W', 'VB_H'].forEach((k) => {
    assert.strictEqual(tok[k], gen[k], 'token ' + k + ' differs between figure-tokens and figure-gen');
  });
  assert.strictEqual(tok.GLYPH_W, 0.6);
  assert.strictEqual(tok.FONT_FLOOR, FONT_FLOOR);
  // The doc renderers must be reachable from the chart module's own dispatch table.
  assert.deepStrictEqual(gen.DOC_TYPES, docs.DOC_TYPES);
});

check('a doc SVG opens with exactly the same two lines a chart SVG does', () => {
  const chart = genSvg({ type: 'bar', series: [{ points: [[0, 1], [1, 2]] }] }, ACCENT).split('\n');
  const doc = docs.renderRoute(readFixture('route-loop'), ACCENT).split('\n');
  assert.strictEqual(doc[0], chart[0], 'the svg root element differs from the chart generator\'s');
  assert.strictEqual(doc[1], chart[1], 'the background rect differs from the chart generator\'s');
  // width and height are NOT redundant with viewBox: the reveal card sizes its image with
  // height:100%/width:auto in a fixed 230px frame (engine/engine.css:266-268), and a viewBox-only
  // SVG in an <img> falls back to the 300x150 default intrinsic size and renders distorted.
  assert.ok(/width="800"/.test(doc[0]) && /height="450"/.test(doc[0]),
    'the root must carry width and height alongside viewBox');
});

check('an apostrophe survives unescaped, and every attribute is double-quoted', () => {
  const svg = docs.renderFacsimile(readFixture('facsimile'), ACCENT);
  assert.ok(svg.indexOf("Whitlock's initials") !== -1,
    'esc() does not escape the apostrophe, so it must appear literally');
  // Since apostrophes pass through unescaped, a single-quoted attribute anywhere would break the
  // document the first time a transcribed label contained one.
  assert.strictEqual(/=\s*'/.test(svg), false, 'a single-quoted attribute would be broken by an apostrophe');
});

check('loading the module touched no DOM and needs no browser', () => {
  assert.strictEqual(typeof document, 'undefined');
});

// ---------------------------------------------------------------------------
// 2. Byte-exact reproduction of every committed fixture
// ---------------------------------------------------------------------------
CASES.forEach((c) => {
  check(c.base + ': ' + c.fn + ' reproduces its committed SVG byte for byte', () => {
    const got = docs[c.fn](readFixture(c.base), ACCENT);
    const want = readExpected(c.base);
    if (got !== want) {
      // Name the first divergence rather than dumping two 400-line strings at the reader.
      const g = got.split('\n'), w = want.split('\n');
      let i = 0;
      while (i < Math.max(g.length, w.length) && g[i] === w[i]) i++;
      assert.fail('first divergence at line ' + (i + 1)
        + ':\n  got:  ' + JSON.stringify(g[i]) + '\n  want: ' + JSON.stringify(w[i]));
    }
  });
});

// ---------------------------------------------------------------------------
// 3. Structural invariants a byte-compare would happily freeze in the wrong state
// ---------------------------------------------------------------------------
CASES.forEach((c) => {
  check(c.base + ': structurally safe (viewBox, no script, no SMIL, no remote href)', () => {
    const svg = docs[c.fn](readFixture(c.base), ACCENT);
    assert.ok(svg.indexOf('viewBox="0 0 800 450"') !== -1, 'missing the 800x450 viewBox');
    assert.strictEqual(svg.indexOf('<script'), -1, 'contains a <script');
    assert.strictEqual(svg.indexOf('<animate'), -1, 'contains SMIL <animate (constraint 7 bans it under art/)');
    assert.strictEqual(svg.indexOf('<set '), -1, 'contains SMIL <set');
    assert.strictEqual(svg.indexOf('href="http'), -1, 'contains a remote href (constraint 5)');
    assert.strictEqual(svg.indexOf('xlink:href="http'), -1, 'contains a remote xlink:href');
    assert.ok(/\n$/.test(svg), 'must end with a trailing newline, as genSvg does');
    assert.ok(svg.trimStart().startsWith('<svg'), 'must start with the svg element');
  });
});

// ---------------------------------------------------------------------------
// 4. Determinism and purity -- the guarantee figure-derive.js rests on
// ---------------------------------------------------------------------------
CASES.forEach((c) => {
  check(c.base + ': deterministic, and does not mutate its dataTable', () => {
    const dt = readFixture(c.base);
    const before = JSON.stringify(dt);
    const a = docs[c.fn](dt, ACCENT);
    const b = docs[c.fn](dt, ACCENT);
    assert.strictEqual(a, b, 'two renders of the same table differ');
    assert.strictEqual(JSON.stringify(dt), before, 'the renderer mutated the dataTable it was given');
  });
});

check('a different accent changes the output, so accent is genuinely threaded through', () => {
  const dt = readFixture('route-loop');
  assert.notStrictEqual(docs.renderRoute(dt, ACCENT), docs.renderRoute(dt, '#c8102e'),
    'accent is ignored, so every pack would draw in the same colour');
});

// ---------------------------------------------------------------------------
// 5. The dispatcher: genSvg must route the four types to these renderers, byte for byte
// ---------------------------------------------------------------------------
CASES.forEach((c) => {
  check(c.base + ': genSvg dispatches type "' + c.type + '" to ' + c.fn + ' with identical bytes', () => {
    const dt = readFixture(c.base);
    assert.strictEqual(genSvg(dt, ACCENT), docs[c.fn](dt, ACCENT));
  });
});

check('genSvg still refuses a dataTable type it does not know, rather than drawing something', () => {
  assert.throws(() => genSvg({ type: 'sankey', sourcePassageId: 'p', nodes: [] }, ACCENT),
    'an unknown type must throw, not return an empty or guessed drawing');
});

// ---------------------------------------------------------------------------
// 6. Geometry: no label may leave the canvas (a plan W0.1 requirement, not taste)
// ---------------------------------------------------------------------------
CASES.forEach((c) => {
  check(c.base + ': every text run lies inside the 800x450 canvas', () => {
    const svg = docs[c.fn](readFixture(c.base), ACCENT);
    const runs = textRuns(svg);
    assert.ok(runs.length > 0, 'no text at all was drawn, so this check is vacuous');
    const bad = [];
    runs.forEach((r) => {
      const ext = horizontalExtent(r);
      if (ext[0] < 0 || ext[1] > VB_W) {
        bad.push('"' + r.text + '" spans ' + ext[0].toFixed(1) + '..' + ext[1].toFixed(1));
      }
      // The SAME ascent/descent model tests/figure-derive.js:126-131 builds its bounding boxes
      // from, so a figure that passes here cannot fail the derive gate's containment check.
      const top = r.y - 0.8 * r.fontSize, bot = r.y + 0.25 * r.fontSize;
      if (top < 0 || bot > VB_H) {
        bad.push('"' + r.text + '" spans y ' + top.toFixed(1) + '..' + bot.toFixed(1));
      }
    });
    assert.deepStrictEqual(bad, [], 'text outside the canvas: ' + bad.join('; '));
  });
});

CASES.forEach((c) => {
  check(c.base + ': no text is authored below the ' + FONT_FLOOR + 'px floor', () => {
    const svg = docs[c.fn](readFixture(c.base), ACCENT);
    const sizes = (svg.match(/font-size="([0-9.]+)"/g) || []).map((s) => parseFloat(/"([0-9.]+)"/.exec(s)[1]));
    assert.ok(sizes.length > 0, 'no font-size was emitted, so this check is vacuous');
    const under = sizes.filter((s) => s < FONT_FLOOR);
    assert.deepStrictEqual(under, [], 'sizes below the floor: ' + under.join(', '));
  });
});

// ---------------------------------------------------------------------------
// 7. Semantic invariants: things a reader would be misled by if they stopped working
// ---------------------------------------------------------------------------
check('facsimile: a redacted line draws a bar and places NO text under it', () => {
  const dt = readFixture('facsimile');
  const svg = docs.renderFacsimile(dt, ACCENT);
  const redacted = dt.lines.filter((l) => l.emphasis === 'redact');
  assert.ok(redacted.length > 0, 'the fixture has no redacted line, so this check is vacuous');
  assert.ok(/data-emphasis="redact"/.test(svg), 'no redaction bar is marked in the output');
  // Nothing a reader could recover: the redacted line contributes no text run at all.
  const texts = textContents(svg).filter(Boolean);
  redacted.forEach((l) => {
    if (l.text) assert.ok(texts.indexOf(l.text) === -1, 'redacted text "' + l.text + '" was drawn anyway');
  });
});

check('facsimile: every authored line and header value is actually drawn', () => {
  const dt = readFixture('facsimile');
  const svg = docs.renderFacsimile(dt, ACCENT);
  const texts = textContents(svg);
  dt.header.forEach((h) => {
    assert.ok(texts.some((t) => t.indexOf(h.value) !== -1), 'header value "' + h.value + '" was not drawn');
  });
  dt.lines.filter((l) => l.emphasis !== 'redact' && l.text).forEach((l) => {
    assert.ok(texts.some((t) => t.indexOf(l.text) !== -1), 'line "' + l.text + '" was not drawn');
  });
  assert.ok(texts.some((t) => t.indexOf(dt.stamp) !== -1), 'the stamp was not drawn');
});

check('facsimile: every column heading and cell is drawn', () => {
  const dt = readFixture('facsimile-columns');
  const svg = docs.renderFacsimile(dt, ACCENT);
  const texts = textContents(svg);
  dt.columns.forEach((col) => {
    assert.ok(texts.some((t) => t.indexOf(col.heading) !== -1), 'heading "' + col.heading + '" was not drawn');
    col.rows.forEach((cell) => {
      if (!cell) return;
      assert.ok(texts.some((t) => t.indexOf(cell) !== -1), 'cell "' + cell + '" was not drawn');
    });
  });
});

check('timeline: an unverified event is drawn dashed AND carries the ? marker', () => {
  const dt = readFixture('timeline-two-track');
  const svg = docs.renderTimeline(dt, ACCENT);
  const unver = dt.events.filter((e) => e.kind === 'unverified');
  assert.ok(unver.length > 0, 'the fixture has no unverified event, so this check is vacuous');
  assert.ok(/data-kind="unverified"/.test(svg), 'no event is marked unverified in the output');
  assert.ok(/stroke-dasharray=/.test(svg), 'nothing is drawn dashed');
  const texts = textContents(svg);
  assert.ok(texts.some((t) => t.indexOf('?') !== -1), 'the ? marker is missing');
});

check('timeline: a verified event is NOT drawn dashed, so the two are distinguishable', () => {
  const single = docs.renderTimeline(readFixture('timeline-single'), ACCENT);
  assert.ok(!/data-kind="unverified"/.test(single), 'a timeline with no unverified event marked one anyway');
  assert.ok(single.indexOf('?') === -1, 'a timeline with no unverified event drew the ? marker anyway');
});

check('timeline: a gap is drawn as a hatched band carrying its own label', () => {
  const dt = readFixture('timeline-two-track');
  const svg = docs.renderTimeline(dt, ACCENT);
  assert.ok(dt.gaps.length > 0, 'the fixture has no gap, so this check is vacuous');
  assert.ok(/data-gap=/.test(svg), 'no gap band is marked in the output');
  // Hatching is explicit diagonal strokes, not a <pattern> in <defs>: no other generator in this
  // repo emits defs or ids, and keeping that shape means nothing depends on id scoping when the
  // same SVG is inlined, thumbnailed and lightboxed.
  assert.strictEqual(svg.indexOf('<defs'), -1, 'a doc figure must not emit <defs>');
  const hatch = (svg.match(/stroke="rgba\(232,238,247,0\.35\)"/g) || []).length;
  assert.ok(hatch >= 4, 'the gap band is not hatched (found ' + hatch + ' hatch strokes)');
  const texts = textContents(svg);
  dt.gaps.forEach((g) => {
    assert.ok(texts.some((t) => t.indexOf(g.label) !== -1), 'gap label "' + g.label + '" was not drawn');
  });
});

check('timeline: a gap caption survives SVG whitespace collapse, so its range and its label stay apart', () => {
  // SVG COLLAPSES CONSECUTIVE WHITESPACE, exactly as HTML does, unless the element carries
  // xml:space="preserve" -- and no SVG this repo generates carries it. The caption used to join
  // "<from> to <to>" to the gap's label with TWO SPACES, so every shipped pack drew
  // "8:22 to 9:04 some forty minutes" with the range running into its label as one garbled clause.
  // A byte-compare could not see it: the two spaces were in the file, and the file was made by the
  // same renderer the fixture came from. Only a browser (or this check) reads what a child reads.
  const dt = readFixture('timeline-two-track');
  const svg = docs.renderTimeline(dt, ACCENT);
  const g = dt.gaps[0];
  assert.ok(g && g.from && g.to && g.label, 'the fixture has no bounded, labelled gap, so this check is vacuous');
  const bounded = g.from + ' to ' + g.to;
  const caption = textContents(svg).find((t) => t.indexOf(bounded) !== -1 && t.indexOf(g.label) !== -1);
  assert.ok(caption, 'no single text run carries both the gap range and its label');
  // Render whitespace the way a browser does, then require a separator that is not whitespace.
  const asRendered = caption.replace(/\s+/g, ' ');
  const between = asRendered.slice(asRendered.indexOf(bounded) + bounded.length, asRendered.indexOf(g.label));
  assert.ok(/[^\s]/.test(between),
    'the range and the label are separated only by whitespace, which SVG collapses to one space: '
    + JSON.stringify(asRendered));

  // NEGATIVE CONTROL: the same caption joined the old way is caught. Without this the check above
  // would pass on any string at all and prove nothing.
  const oldStyle = bounded + '  ' + g.label;
  const oldRendered = oldStyle.replace(/\s+/g, ' ');
  const oldBetween = oldRendered.slice(oldRendered.indexOf(bounded) + bounded.length, oldRendered.indexOf(g.label));
  assert.ok(!/[^\s]/.test(oldBetween), 'the negative control does not reproduce the old defect, so it discriminates nothing');
});

check('timeline: every authored event label and time is drawn', () => {
  const dt = readFixture('timeline-two-track');
  const texts = textContents(docs.renderTimeline(dt, ACCENT));
  dt.events.forEach((e) => {
    assert.ok(texts.some((t) => t.indexOf(e.label) !== -1), 'event "' + e.label + '" was not drawn');
    assert.ok(texts.some((t) => t.indexOf(e.t) !== -1), 'time "' + e.t + '" was not drawn');
  });
  dt.tracks.forEach((tr) => {
    assert.ok(texts.some((t) => t.indexOf(tr) !== -1), 'track "' + tr + '" was not labelled');
  });
});

check('schematic: every node label and every edge label is drawn', () => {
  ['schematic-flow', 'schematic-plan'].forEach((base) => {
    const dt = readFixture(base);
    const texts = textContents(docs.renderSchematic(dt, ACCENT));
    dt.nodes.forEach((n) => {
      assert.ok(texts.some((t) => t.indexOf(n.label) !== -1), base + ': node "' + n.label + '" was not drawn');
    });
    (dt.edges || []).filter((e) => e.label).forEach((e) => {
      assert.ok(texts.some((t) => t.indexOf(e.label) !== -1), base + ': edge label "' + e.label + '" was not drawn');
    });
  });
});

check('schematic: layout "plan" honours authored x/y, and the computed layouts ignore them', () => {
  const planDt = readFixture('schematic-plan');
  const moved = JSON.parse(JSON.stringify(planDt));
  moved.nodes[0].x = 70;
  assert.notStrictEqual(docs.renderSchematic(planDt, ACCENT), docs.renderSchematic(moved, ACCENT),
    'layout "plan" ignored an authored x, so a floor plan cannot be drawn to the passage');

  const flowDt = readFixture('schematic-flow');
  const withXY = JSON.parse(JSON.stringify(flowDt));
  withXY.nodes[0].x = 90; withXY.nodes[0].y = 90;
  assert.strictEqual(docs.renderSchematic(flowDt, ACCENT), docs.renderSchematic(withXY, ACCENT),
    'layout "flow-lr" honoured x/y, so a computed layout is not actually computed');
});

check('route: every stop number, label and note is drawn, in authored order', () => {
  ['route-loop', 'route-line'].forEach((base) => {
    const dt = readFixture(base);
    const svg = docs.renderRoute(dt, ACCENT);
    const texts = textContents(svg);
    dt.stops.forEach((s) => {
      assert.ok(texts.some((t) => t.indexOf(s.label) !== -1), base + ': stop "' + s.label + '" was not drawn');
      assert.ok(texts.some((t) => t.indexOf(String(s.n)) !== -1), base + ': number ' + s.n + ' was not drawn');
      if (s.note) assert.ok(texts.some((t) => t.indexOf(s.note) !== -1), base + ': note "' + s.note + '" was not drawn');
    });
    const order = dt.stops.map((s) => svg.indexOf('>' + s.label + '<'));
    const sorted = order.slice().sort((a, b) => a - b);
    assert.deepStrictEqual(order, sorted, base + ': stops are not emitted in authored order');
  });
});

check('route: a loop closes and a line does not, so the two paths are distinguishable', () => {
  const loop = docs.renderRoute(readFixture('route-loop'), ACCENT);
  const line = docs.renderRoute(readFixture('route-line'), ACCENT);
  assert.ok(/data-path="loop"/.test(loop), 'the loop route is not marked as a loop');
  assert.ok(/data-path="line"/.test(line), 'the line route is not marked as a line');
  assert.strictEqual(/data-path="loop"/.test(line), false, 'a line route was drawn as a loop');
});

// ---------------------------------------------------------------------------
// 8. Refusals: the renderers must reject what they cannot draw truthfully, as genSvg does
// ---------------------------------------------------------------------------
check('every renderer refuses an empty table rather than drawing an empty frame', () => {
  assert.throws(() => docs.renderTimeline({ type: 'timeline', events: [] }, ACCENT), /event/i);
  assert.throws(() => docs.renderFacsimile({ type: 'facsimile' }, ACCENT), /line|column|header/i);
  assert.throws(() => docs.renderSchematic({ type: 'schematic', nodes: [] }, ACCENT), /node/i);
  assert.throws(() => docs.renderRoute({ type: 'route', stops: [] }, ACCENT), /stop/i);
});

check('schematic refuses an edge naming a node that does not exist', () => {
  const dt = readFixture('schematic-flow');
  dt.edges.push({ from: 'fish', to: 'ghost', style: 'arrow' });
  assert.throws(() => docs.renderSchematic(dt, ACCENT), /ghost/,
    'an edge to a missing node must throw, not be silently dropped');
});

check('timeline refuses an event on a track it never declared', () => {
  const dt = readFixture('timeline-two-track');
  dt.events.push({ t: '9:00 p.m.', label: 'stray', track: 'nowhere' });
  assert.throws(() => docs.renderTimeline(dt, ACCENT), /nowhere/,
    'an event on an undeclared track must throw, not be silently dropped');
});

check('every renderer refuses a table whose type does not match it', () => {
  assert.throws(() => docs.renderTimeline(readFixture('route-loop'), ACCENT), /timeline/i);
  assert.throws(() => docs.renderRoute(readFixture('timeline-single'), ACCENT), /route/i);
});

// AN EDGE LABEL MUST CLEAR EVERY OTHER EDGE LABEL. Third step of a rule the renderer already
// enforced against boxes and against connectors, and the last one it was missing: two labels could
// occupy the identical rectangle and still render. Found by LOOKING at a plan where an arrow
// arriving horizontally and an arrow arriving vertically met at the same node, which printed
// "The badge reads green" straight through "straight down".
// A CONTRAST ROW IN A FACSIMILE HEADER draws both halves at the same weight, so the pair block does
// not teach "dim label, bright value" and then use the same shape for two things that are equals.
check('a header row marked contrast draws both halves at the same size; an unmarked one does not', () => {
  const base = {
    type: 'facsimile', docKind: 'memo', title: 'a memo',
    header: [{ label: 'the same beacon test', value: 'three different tunnels' }],
    lines: [{ text: 'a plain line' }],
  };
  const plain = docs.renderFacsimile(JSON.parse(JSON.stringify(base)), ACCENT);
  const withContrast = JSON.parse(JSON.stringify(base));
  withContrast.header[0].contrast = true;
  const marked = docs.renderFacsimile(withContrast, ACCENT);

  const sizeOf = (svg, txt) => {
    // No constructed regex here. The first version built one with '(\d+)' inside a SINGLE-QUOTED
    // JS string, where \d collapses to a plain d, so the pattern hunted for the letter d and matched
    // nothing -- the same trap tests/figure-prose.js hit with 'hatched\s+'. Splitting on the literal
    // text has no escaping to get wrong.
    const seg = svg.split('>' + txt + '<')[0];
    const m = seg.lastIndexOf('font-size="');
    if (m === -1) return null;
    return Number(seg.slice(m + 11, seg.indexOf('"', m + 11)));
  };
  const labelPlain = sizeOf(plain, 'the same beacon test');
  const valuePlain = sizeOf(plain, 'three different tunnels');
  const labelMarked = sizeOf(marked, 'the same beacon test');
  const valueMarked = sizeOf(marked, 'three different tunnels');

  assert.ok(labelPlain && valuePlain && labelMarked && valueMarked, 'all four runs must be found');
  assert.ok(labelPlain < valuePlain, 'CONTROL: an ordinary row keeps the dim small label');
  assert.strictEqual(labelMarked, valueMarked, 'a contrast row sets both halves at one size');
  // And the flag is what does it: without it the two sizes differ, with it they match.
  assert.notStrictEqual(labelPlain, labelMarked, 'the flag must actually change the label');
});

// AN ORDINAL LANE POSITIONS BY TIME, NOT BY INDEX. Two entries at the same stated time must land
// on the same vertical, because evenly spaced dots read as distinct moments and the drawing would
// otherwise assert an order the clock does not give.
check('an ordinal timeline puts two events at the SAME time on the same vertical', () => {
  const dt = {
    type: 'timeline', title: 'tied', tracks: ['the rule', 'the log'],
    events: [
      { t: 'ten fourteen', track: 'the log', label: 'goes in' },
      { t: 'ten twenty', track: 'the rule', label: 'checks in' },
      { t: 'ten twenty', track: 'the log', label: 'only the hiss' },
      { t: 'ten twenty-two', track: 'the rule', label: 'calls it off' },
    ],
  };
  const svg = docs.renderTimeline(dt, ACCENT);
  const cx = [...svg.matchAll(/<circle cx="([\d.]+)" cy="([\d.]+)"/g)].map((m) => [+m[1], +m[2]]);
  assert.strictEqual(cx.length, 4, 'four markers');
  const tied = cx.filter((p) => Math.abs(p[0] - cx[1][0]) < 0.01);
  assert.strictEqual(tied.length, 2, 'the two "ten twenty" events must share an x');
  assert.notStrictEqual(tied[0][1], tied[1][1], 'and be separated by their tracks, not by x');
  // NEGATIVE DIRECTION: three DISTINCT times give three distinct x values, so the check above is
  // about ties and not about everything collapsing.
  const xs = new Set(cx.map((p) => p[0].toFixed(2)));
  assert.strictEqual(xs.size, 3, 'three distinct times give three distinct positions');
});

check('NEGATIVE CONTROL: two events tied on the SAME track are refused, not drawn on one point', () => {
  const dt = {
    type: 'timeline', title: 'tied', tracks: ['the log'],
    events: [
      { t: 'ten fourteen', track: 'the log', label: 'goes in' },
      { t: 'ten twenty', track: 'the log', label: 'checks in' },
      { t: 'ten twenty', track: 'the log', label: 'only the hiss' },
    ],
  };
  assert.throws(() => docs.renderTimeline(dt, ACCENT), /share the time/,
    'two events at one time on one track would be drawn on top of each other');
});

check('a key label and a key lead both WRAP rather than forcing a transcription to be shortened', () => {
  const dt = {
    type: 'timeline', title: 'long', tracks: ['the log'],
    events: [
      { t: 'ten twenty-two and eleven seconds', track: 'the log', label: 'nothing on the radio but the hiss' },
      { t: 'ten fourteen', track: 'the log', label: 'goes in' },
    ],
  };
  const svg = docs.renderTimeline(dt, ACCENT);
  assert.ok(svg.includes('tspan'), 'a long lead or label wraps');
  const flat = svg.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ');
  assert.ok(flat.includes('ten twenty-two and eleven seconds'),
    'the wrapped lead still reads as one collapsed string, which is what the fidelity gate reads');
  assert.ok(flat.includes('nothing on the radio but the hiss'), 'and so does the wrapped label');
});

// A LINE AT THE FOOT OF A PAGE IS ITS OWN THING, not a second column. Cold Signal's log card
// authored "one more line at the bottom of the page" as a parallel COLUMN, which split one sentence
// across four ruled rows so each fragment paired with the log entry beside it -- four facts the
// record does not contain. The shape had no way to say "a line at the foot", so the author reached
// for the nearest thing that rendered.
check('a facsimile draws a footnote at the FOOT of the card, below its own rule, and it may wrap', () => {
  const dt = {
    type: 'facsimile', docKind: 'minutes', title: 'the log sheets',
    columns: [{ heading: 'what happened', rows: ['entry at ten fourteen', 'exit at ten forty-one'] }],
    footnote: 'Thirty seconds lost on the second floor landing, cause unknown, no action taken.',
  };
  const svg = docs.renderFacsimile(dt, ACCENT);
  assert.ok(svg.includes('Thirty seconds lost'), 'the footnote must be drawn');
  // It is BELOW the last column row, which is the whole claim the field makes.
  const lastRow = svg.lastIndexOf('exit at ten forty-one');
  const foot = svg.lastIndexOf('Thirty seconds lost');
  assert.ok(foot > lastRow, 'the footnote must come after the table, not before it');
  // Wrapped rather than refused: one <text> with two <tspan>s, so the fidelity gate still reads it
  // as one collapsed string.
  const el = svg.slice(foot - 200, foot + 300);
  assert.ok(el.includes('tspan'), 'a long footnote wraps instead of being refused');
});

check('NEGATIVE CONTROL: a footnote with no room at the foot of the card is REFUSED', () => {
  const rows = [];
  // EIGHT rows, measured: eight renders without a footnote and refuses with one, so the footnote
  // is the only difference between this check and the control below it. Nine rows refuses either
  // way, on the table's own fit check, and would have proved nothing -- which is what the first
  // version of this pair did.
  for (let i = 0; i < 8; i++) rows.push('a log entry number ' + i);
  const dt = {
    type: 'facsimile', docKind: 'minutes', title: 'the log sheets',
    columns: [{ heading: 'what happened', rows }],
    footnote: 'Thirty seconds lost on the second floor landing, cause unknown, no action taken.',
  };
  assert.throws(() => docs.renderFacsimile(dt, ACCENT), /footnote/,
    'a card whose table reaches the foot must refuse the footnote, not draw it over the table');
});

check('CONTROL: the same tall card WITHOUT the footnote renders, so the refusal is the FOOTNOTE', () => {
  const rows = [];
  for (let i = 0; i < 8; i++) rows.push('a log entry number ' + i);
  const dt = {
    type: 'facsimile', docKind: 'minutes', title: 'the log sheets',
    columns: [{ heading: 'what happened', rows }],
  };
  const svg = docs.renderFacsimile(dt, ACCENT);
  assert.ok(svg.includes('a log entry number 7'), 'the table alone should still draw');
});

// THE REAL GEOMETRY THAT SHIPPED THE DEFECT, not a synthetic stand-in. Two arrows arrive at
// "shelf", one horizontally and one vertically, and their labels were printed one straight through
// the other -- "The badge reads green" across "straight down" -- while every gate stayed green.
// Verified to be a true discriminator: with the label-vs-label test removed from the renderer this
// table RENDERS, and with it in place it is REFUSED. A first attempt used an invented three-node
// fixture which was refused either way, by the older connector rule, and so proved nothing; that
// version passed with the new check deleted.
const OVERLAPPING_LABELS = {
  type: 'schematic', layout: 'plan', title: 'Frostbank Storage',
  nodes: [
    { id: 'doors', label: 'eleven doors', shape: 'box', x: 8, y: 72 },
    { id: 'twelfth', label: 'The twelfth', shape: 'box', x: 42, y: 72 },
    { id: 'panel', label: 'a single reader panel', shape: 'box', x: 42, y: 92 },
    { id: 'camera', label: "the room's only camera", shape: 'box', x: 86, y: 26 },
    { id: 'shelf', label: 'a raised shelf', shape: 'box', x: 86, y: 72 },
  ],
  edges: [
    { from: 'doors', to: 'twelfth', label: 'a corridor so featureless', style: 'arrow' },
    { from: 'panel', to: 'twelfth', style: 'line' },
    { from: 'twelfth', to: 'shelf', label: 'The badge reads green', style: 'arrow' },
    { from: 'camera', to: 'shelf', label: 'straight down', style: 'arrow' },
  ],
};

check('NEGATIVE CONTROL: two edge labels that would overlap are REFUSED, not printed over each other', () => {
  const dt = JSON.parse(JSON.stringify(OVERLAPPING_LABELS));
  assert.throws(() => docs.renderSchematic(dt, ACCENT), /cannot be placed/,
    'two labels sharing one rectangle must be refused, not drawn one through the other');
});

check('CONTROL: the same plan with one of the two labels dropped renders, so the refusal is the OVERLAP', () => {
  // Without this, the refusal above could be about the geometry rather than about the labels.
  const dt = JSON.parse(JSON.stringify(OVERLAPPING_LABELS));
  delete dt.edges.find((e) => e.from === 'camera').label;
  const svg = docs.renderSchematic(dt, ACCENT);
  assert.ok(svg.includes('The badge reads green'), 'the one remaining label should draw');
});

console.log(failures ? 'figure-docs.test: ' + failures + ' FAILURE(S)' : 'figure-docs.test: all clean');
process.exit(failures ? 1 : 0);
